yarnPath: .yarn/releases/yarn-3.2.4.cjs

nodeLinker: node-modules

packageExtensions:
  "@shopify/eslint-plugin@42":
    peerDependencies:
      "@babel/core": "*"
      prettier: "*"
  eslint-config-hardcore@25:
    peerDependencies:
      "@babel/core": "*"
  eslint-plugin-styled-components-a11y@1:
    peerDependencies:
      eslint: "*"
      eslint-plugin-import: "*"
      eslint-plugin-react: "*"
